# Site settings
title: Tennis
email: pat5547@gmail.com
description: Bayesian time-series models for tennis outcomes
url: "http://sportmodel.github.io/tennis"
baseurl: ""
github_username:  sportModel

# Build settings
markdown: kramdown
exclude: [new]

# Defaults
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      rel: "../../../"
  -
    scope:
      path: ""
    values:
      layout: "default"
